# Generated by Django 3.0.2 on 2020-01-10 09:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='This is the amount of hits that the user currently has. Credit is reduced as the user matches and downloads files.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='duplicated_last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Duplicated last login'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='previous_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Previous login'),
        ),
    ]
